#KERNELDIR ?= /run/current-system/kernel/lib/modules/$(shell uname -r)/build
obj-m += tsu_module.o

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
